version: '3.9'

services:
  db:
    image: postgres:14.6
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_PASSWORD: 'climate'
      POSTGRES_USER: 'climate'
      POSTGRES_DB: 'climatedb'
    restart: always
    healthcheck:
      test: pg_isready --dbname=climatedb -U climate
      interval: 2s
      timeout: 3s
      retries: 40

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/app
    env_file: .local.env
    restart: always
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 5001
    ports:
      - 5001:5001
    depends_on:
      - db
