"""Deleted price table

Revision ID: 6e56615db303
Revises: b6b43fb509c3
Create Date: 2023-06-16 10:24:55.518458

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6e56615db303"
down_revision = "b6b43fb509c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price")
    op.add_column("item", sa.Column("gbp", sa.Float(), nullable=True))
    op.add_column("item", sa.Column("eur", sa.Float(), nullable=True))
    op.add_column("item", sa.Column("usd", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "usd")
    op.drop_column("item", "eur")
    op.drop_column("item", "gbp")
    op.create_table(
        "price",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "gbp",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "eur",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "usd",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("item_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["item_id"], ["item.id"], name="price_item_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="price_pkey"),
    )
    # ### end Alembic commands ###
