"""Typo in price

Revision ID: b6b43fb509c3
Revises: fe784ec9107f
Create Date: 2023-06-16 10:23:25.483158

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6b43fb509c3"
down_revision = "fe784ec9107f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "price", sa.Column("item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.drop_constraint("price_store_id_fkey", "price", type_="foreignkey")
    op.create_foreign_key(None, "price", "item", ["item_id"], ["id"])
    op.drop_column("price", "store_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "price", sa.Column("store_id", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "price", type_="foreignkey")
    op.create_foreign_key("price_store_id_fkey", "price", "item", ["store_id"], ["id"])
    op.drop_column("price", "item_id")
    # ### end Alembic commands ###
