"""lat lon changes

Revision ID: b6f5f7fa629a
Revises: 6e56615db303
Create Date: 2023-06-20 13:35:04.251043

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6f5f7fa629a"
down_revision = "6e56615db303"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("location")
    op.add_column("store", sa.Column("lat", sa.Float(), nullable=False))
    op.add_column("store", sa.Column("lon", sa.Float(), nullable=False))
    op.alter_column("store", "location", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("store", "location", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("store", "lon")
    op.drop_column("store", "lat")
    op.create_table(
        "location",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="location_pkey"),
    )
    # ### end Alembic commands ###
