"""Colours change

Revision ID: fe784ec9107f
Revises: 4445af6be318
Create Date: 2023-06-16 10:00:14.472801

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "fe784ec9107f"
down_revision = "4445af6be318"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "colour",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("colours")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "colours",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("store_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"], ["item.id"], name="colours_store_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="colours_pkey"),
    )
    op.drop_table("colour")
    # ### end Alembic commands ###
